---
- name: Display Running Configuration on Cisco Switches
  hosts: switches  # Ensure this group is defined in your inventory
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Retrieve running configuration
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: running_config

    - name: Print running configuration
      debug:
        var: running_config.stdout[0]
