---
- name: Test Connectivity to Cisco Switch
  hosts: switches
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Run sshpass to SSH into Cisco device and execute 'show ip int brief'
      command: sshpass -p 'test' ssh -T -o StrictHostKeyChecking=no test@192.168.99.101 "show ip int brief"
      register: ip_int_brief_output
      ignore_errors: yes

    - name: Print 'show ip int brief' command output
      debug:
        var: ip_int_brief_output.stdout

    - name: Retrieve running configuration
      ios_command:
        commands:
          - show running-config
      register: running_config
      ignore_errors: yes

    - name: Print running configuration
      debug:
        var: running_config.stdout[0]
      when: running_config is defined
