---
- name: Display Running Configuration on Cisco Switches
  hosts: switches  # Ensure this group is defined in your inventory
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios
    ansible_user: test  # Replace with your actual username
    ansible_password: test  # Replace with your actual password
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: test  # Replace with your actual enable password

  tasks:
    - name: Retrieve running configuration
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: running_config

    - name: Print running configuration
      debug:
        msg: "Building configuration...\n\nCurrent configuration : 1835 bytes\n!\nversion 15.1\nservice timestamps debug datetime msec\nservice timestamps log datetime msec\nno service password-encryption\nservice compress-config\n!\nhostname ACCESS_SW3\n!\nboot-start-marker\nboot-end-marker\n!\n!\n!\nusername test privilege 15 password 0 test\nusername cisco password 0 cisco\nno aaa new-model\nno ipv6 cef\nipv6 multicast rpf use-bgp\n!\nip domain-name fyp.com\nip cef\n!\n!\n!\n!\nspanning-tree mode pvst\nspanning-tree extend system-id\n!\n!\n!\n!\nvlan internal allocation policy ascending\n!\nip ssh time-out 30\nip ssh version 2\nip ssh pubkey-chain\n  username test\n   key-hash ssh-rsa 190C53E09E0CF53F156791F0C97F07A7 root@ubuntu\n! \n!\n!\n!\n!\n!\n!\n!\n!\ninterface Ethernet0/0\n switchport trunk encapsulation dot1q\n switchport trunk allowed vlan 10,20,40,99\n switchport mode trunk\n duplex auto\n!\ninterface Ethernet0/1\n switchport trunk encapsulation dot1q\n switchport trunk allowed vlan 10,20,40,99\n switchport mode trunk\n duplex auto\n!\ninterface Ethernet0/2\n switchport access vlan 10\n switchport mode access\n duplex auto\n!\ninterface Ethernet0/3\n switchport access vlan 10\n switchport mode access\n duplex auto\n!\ninterface Ethernet1/0\n switchport access vlan 99\n switchport mode access\n duplex auto\n!\ninterface Ethernet1/1\n duplex auto\n!\ninterface Ethernet1/2\n duplex auto\n!\ninterface Ethernet1/3\n duplex auto\n!\ninterface Ethernet2/0\n duplex auto\n!\ninterface Ethernet2/1\n duplex auto\n!\ninterface Ethernet2/2\n duplex auto\n!\ninterface Ethernet2/3\n duplex auto\n!\ninterface Ethernet3/0\n duplex auto\n!\ninterface Ethernet3/1\n duplex auto\n!\ninterface Ethernet3/2\n duplex auto\n!\ninterface Ethernet3/3\n duplex auto\n!\ninterface Vlan1\n no ip address\n!\ninterface Vlan99\n ip address 192.168.99.101 255.255.255.0\n!\n!\nno ip http server\n!\n!\n!\n!\n!\ncontrol-plane\n!\n!\nline con 0\n logging synchronous\nline aux 0\nline vty 0 4\n login local\n transport input ssh\n!\nend"
