---
- name: Configure Cisco switch and create VLAN
  hosts: ACCESS_SW1
  gather_facts: no
  connection: network_cli
    - name: Ensure VLAN 100 exists
      cisco.ios.ios_config:
        lines:
          - vlan 100

    - name: Name VLAN 100 as Flower
      cisco.ios.ios_config:
        lines:
          - name Flower
        parents:
          - vlan 100
