---
- name: Configure Cisco switch and create VLAN
  hosts: ACCESS_SW1
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios
    ansible_user: test  # Replace with your actual username
    ansible_password: test  # Replace with your actual password
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: test  # Replace with your actual enable password

  tasks:
    - name: Run sshpass to SSH into Cisco device and execute 'show ip int brief'
      command: sshpass -p 'test' ssh -T -o StrictHostKeyChecking=no test@192.168.99.106 "show ip int brief"
      register: ip_int_brief_output
      ignore_errors: yes

    - name: Ensure VLAN 100 exists
      cisco.ios.ios_config:
        lines:
          - vlan 100

    - name: Name VLAN 100 as Flower
      cisco.ios.ios_config:
        lines:
          - name Flower
        parents:
          - vlan 100
