- name: Configure Cisco switch and create VLAN
  hosts: ACCESS_SW1
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios
    ansible_user: test  # Replace with your actual username
    ansible_password: test  # Replace with your actual password
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: test  # Replace with your actual enable password

  tasks:
    - name: Ensure VLAN 200 exists
      cisco.ios.ios_config:
        lines:
          - vlan 200

    - name: Name VLAN 200 as FYP
      cisco.ios.ios_config:
        lines:
          - name FYP
        parents:
          - vlan 200
