---
- name: Check if paramiko is installed and install if necessary
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if paramiko is installed
      command: python -c "import paramiko"
      register: paramiko_check
      ignore_errors: yes

    - name: Install paramiko if not present
      include_playbook: install_paramiko.yml
      when: paramiko_check.failed

- name: Create VLAN if it doesn't exist on a Cisco switch
  hosts: switches
  gather_facts: no
  connection: network_cli

  vars:
    vlan_id: 40
    vlan_name: "Guest"
    interface: "GigabitEthernet0/2"

  tasks:
    - name: Collect facts about VLAN "{{ vlan_id }}" on the device
      cisco.ios.ios_command:
        commands:
          - "show vlan id {{ vlan_id }}"
      register: sh_vlan_output

    - name: Check if VLAN exists
      set_fact:
        vlan_exists: "{{ 'VLAN' in sh_vlan_output.stdout[0] }}"

    - name: Add VLAN if it does not exist
      cisco.ios.ios_config:
        lines:
          - "vlan {{ vlan_id }}"
          - "name {{ vlan_name }}"
        parents: []
      when: not vlan_exists

    - name: Assign interface to VLAN
      cisco.ios.ios_config:
        lines:
          - "switchport mode access"
          - "switchport access vlan {{ vlan_id }}"
        parents: ["interface {{ interface }}"]
      when: not vlan_exists

    - name: Save running to start-config when modified
      cisco.ios.ios_config:
        save_when: modified
